// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDc0Tcf9CD2Cs9bdyQij-q-1n6mivGvrQ',
    appId: '1:786554390432:web:8b35309a92d3e6729406c5',
    messagingSenderId: '786554390432',
    projectId: 'testing-55b8f',
    authDomain: 'testing-55b8f.firebaseapp.com',
    storageBucket: 'testing-55b8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_trqrYtJN6qf--bPuniVAJZZAZEAtx4',
    appId: '1:786554390432:android:aa82bfcfce6625be9406c5',
    messagingSenderId: '786554390432',
    projectId: 'testing-55b8f',
    storageBucket: 'testing-55b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADU87gXV8nBbtQJYXUfUMY7_n5EOYoAgw',
    appId: '1:786554390432:ios:144f80b7e88288989406c5',
    messagingSenderId: '786554390432',
    projectId: 'testing-55b8f',
    storageBucket: 'testing-55b8f.firebasestorage.app',
    iosBundleId: 'com.example.maternalhealthcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADU87gXV8nBbtQJYXUfUMY7_n5EOYoAgw',
    appId: '1:786554390432:ios:144f80b7e88288989406c5',
    messagingSenderId: '786554390432',
    projectId: 'testing-55b8f',
    storageBucket: 'testing-55b8f.firebasestorage.app',
    iosBundleId: 'com.example.maternalhealthcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDc0Tcf9CD2Cs9bdyQij-q-1n6mivGvrQ',
    appId: '1:786554390432:web:e90ee4c1c300796e9406c5',
    messagingSenderId: '786554390432',
    projectId: 'testing-55b8f',
    authDomain: 'testing-55b8f.firebaseapp.com',
    storageBucket: 'testing-55b8f.firebasestorage.app',
  );
}